# -*- coding: utf-8 -*-
"""Panda Import and Execute.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17ukhXKfTLi35L5F_RzArJmBlk8b7iuvM

# Install & import
"""

import pandas as pd

import numpy as np
data = np.array(['a','b','c','d'])
s = pd.Series(data)

print(s)

fruits = {
    'apples' : [3,2,0,1],
    'oranges' : [0,3,7,2],
}

df = pd.DataFrame(fruits)
df

df = pd.DataFrame(fruits, index=['A','B','C','D'])
df

pd.DataFrame({'Comment1' : ['I liked it.', 'Nice'],
              'Comment2' : ['Pretty good', 'Awesome']}, 
              index = ['Product A', 'Product B'])

data = [['Alex',10],['Bob',12],['Clarke',15]]
df = pd.DataFrame(data, columns=['Name', 'Age'])

df

df.info()

"""# Working with Column"""

df["Name"]

df.Name

df[['Name','Age']]

"""Add Column"""

df['Score'] = pd.Series([10,20,30])
print(df)

"""Delete Column"""

del df['Score']

df

"""# Working with Row"""

df.loc[1] #locate for particular label

df.iloc[1] #Locate integer locations

df.iloc[:, 0:3]

df

"""Add new Row"""

df2 = pd.DataFrame([['Smith', 15.0,50]])
df = df.append(df2)
df

df.drop(0) #by index

"""# Reading data from CSV"""

#import file from Google Drive
#drive.mount('/content/sample_data/california_housing_test.csv')

#df.to_csv('new_purchase.csv')
#df.to_json('new_purchase.json')

# df = pd.read_excel()

df = pd.read_csv('/content/sample_data/california_housing_test.csv')
df

df = pd.read_json('/content/sample_data/anscombe.json')
df

df.loc[1:3]

df.iloc[1:3]

"""# Basic Functionality"""

df.head(3)

df.tail()

df.shape

df.info()

df.axes

df.empty

df.ndim

df.size

df.values

df.T

"""# Descriptive Statistics"""

df = pd.read_csv("/content/sample_data/california_housing_train.csv")
df

df.sum()

df['latitude'].sum()

df.sum(1)

df.max()

"""# Some Functions & Description"""

df.describe()

df.describe(include='all')

df.population.unique()