# -*- coding: utf-8 -*-
"""Python Basic Code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_oY8iVqrSbuKL1XPb8bHa-M_Xubm69SU

# First code of AI
"""

print("Hello World!")

"""# Type"""

x = 10
type(x)

type('name')

type(10.5)

"""# Arithmatic Operator"""

a=4
b=6
c=3
d=5
e=9
f=2
equation = a+b*d/c-3+8*e-f
equation1 = (a+((b*d)/c)-3+(8*e)-f)
print(equation)
print(equation1)

"""# Relational Operator"""

x = 105
y = 100

x>y

x<y

x==y

"""# Print Function"""

print(' this is a longer string, so we \
split it over two lines')

print('sum is',7+3)

"""**Truncate remember**#remember"""

print("""hello,\
this is \
a
multiline
string""")

print("""Hi,
This is our First lab class.
Welcome Everyone.""")

"""# Precision Handling"""

7/3

a = 3.4536475856

print("%.3f" %a)

a=10/3
print("%.2f" %a)

"""# Getting Input from user"""

name = input("My Name is : ")

print(name)

"""# Concatenation"""

value1 = input("Enter first value: ")
value2 = input("Enter second value: ")

total = value1 + value2

print(total)

type(total)

a = input("Enter a value : ")

type(a)

"""# Getting an interger input"""

b = int(input('Enter an integer: '))

type(b)

"""# Taking Multiple input"""

a, b = input().split(',')

print(a,b)

print(type(a))

a, b, c, d, e = input().split(' ')

print(a,b,c,d,e)

type(a)

"""# Min & Max"""

val1 = int(input("Enter value1:"))
val2 = int(input("Enter value2:"))
val3 = int(input("Enter value3:"))

min(val1,val2,val3)

max(val1,val2,val3)