# -*- coding: utf-8 -*-
"""Statements and Loops.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SYGikNUTvdyKAuSHPeXvES3JE_mh1Oa_

# If Else Statement
"""

grade = 85
if grade >= 60:
  print('passed')
  print()

grade = 55
if grade >= 60:
  print('Passed')
else:
  print('Fail')
  print()

grade = 50

result = 'passed' if grade >= 60 else 'Fail'

print(result)

"""# Class Work

Write a program for the following statement:

age = take user input

if

  age greater than 0 and less than 13, Print "Child"

  age greater than or equal 13 and less than 18, print"Teen"

  age greater than or equal 18 and less than or equal 35, print "Young"

  age greater than or equal 36 and less then 100, print "Old"

  OR print "Error"
"""

age = int(input("Enter Age : "))

if age > 0 and age < 13:
  print("Child")
elif age >= 13 and age < 18:
  print("Teen")
elif age > 18 and age <= 35:
  print("Young")
elif age >= 36 and age <100:
  print("Old")
else:
  print("Error")

"""Write a program to check Odd or even number."""

n = int(input("Enter an interger: "))

if (n % 2) == 0:
  print("Even Number")
else:
  print("Odd Number")

"""# While Statement"""

num = 1

while num < 10:
  print(num, end=" ")
  num+=1

num2 = int(input("Enter a number: "))

while num2 < 10:
  print(num2, end=" ")
  num2+=1

value = int(input("Enter a number: "))
i = 1
while i <=value:
  if(i%2==0):
    print(i)
  i = i+1

for i in "CSE312":
  print(i)

for character in ["Programming", '2', '3', '4']:
  print(i)

"""Build in Range function"""

for i in range(0,10,2):
  print(i)

for counter in range(15):
  print(counter,end=" ")

total = 0
for number in range(1000001):
  total = total + number

print(total)

for number in range(0,10,4):
  print(number, end=" ")

for number in range(10,-1,-1):
  print(number, end=" ")

number = int(input())

for i in range(1,11):
  print(number, "X", i,"=", number*i)

"""Nested loop"""

for i in range(11):
  for j in range(i):
    print('*', end='')
  print('')

"""Break Statement"""

for number in range(10):
  if number==7:
    break
  print(number, end=" ")

"""Continue statement"""

for number in range(10):
  if number==5:
    continue
  print(number, end=" ")