# -*- coding: utf-8 -*-
"""Upload data set and exercise of numpy and pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OOzrAiQ762AldignNbvx2bB8CI271kRZ

#4
"""

import pandas as pd

df = pd.read_csv("/content/sample_data/california_housing_test.csv")

print(df)

df.drop(0)

df.head(10)

df.tail(6)

df

"""# 3"""

import numpy as np

a = np.array([1,2,3,4,5])
a

b = a.size

print(b)

b = np.array([[1,2,3],[4,5,6]])
b

d = np.info(a)

d = np.info(b)

"""# 2"""

num = int(input("Enter a Value: "))

if(num % 2 == 0):
  print(num,"is Even")
else:
  print(num,"is Odd")

"""#1"""

num = int(input("Input Number: "))

if(num >= 80):
  print("Grade A")
elif(num >= 70):
  print("Grade B")
elif(num >= 60):
  print("Grade C")
elif(num >= 50):
  print("Grade D")
elif(num >= 40):
  print("Grade E")
else:
  print("Failed")